import PDFDocument from "pdfkit";
import path from "path";
import fs from "fs";

// ─── SHARED HELPERS ───────────────────────────────────────────────────────────

const blueColor = "#1565c0";
const lightBlueBg = "#e3f2fd";
const sectionHeaderColor = [0, 102, 102];
const margin = 30;
const pageWidth = 595;
const contentWidth = pageWidth - margin * 2;

const getReportDate = () =>
  new Date().toLocaleDateString("en-GB", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });

const drawHeader = (doc, reportDate) => {
  // Logos
  try {
    const vyuhaaLogo = path.resolve(process.cwd(), "assets", "vyuhaa.png");
    const cerviLogo = path.resolve(process.cwd(), "assets", "cerviai.png");
    if (fs.existsSync(vyuhaaLogo)) doc.image(vyuhaaLogo, margin, 20, { height: 45 });
    if (fs.existsSync(cerviLogo)) doc.image(cerviLogo, 460, 25, { height: 32 });
  } catch (e) {
    console.log("Logos missing");
  }

  // Address Bar
  const addressBarY = 80;
  doc.rect(margin, addressBarY, contentWidth, 42).fill(lightBlueBg);

  doc
    .fontSize(8).fillColor("black")
    .font("Helvetica-Bold")
    .text("Address: ", margin + 15, addressBarY + 8, { continued: true })
    .font("Helvetica")
    .text("C15, First floor, BioValley Incubation Center I-Hub, AMTZ Campus, Visakhapatnam, Andhra Pradesh 530031", { continued: false });

  const contactLineY = addressBarY + 24;

  doc.font("Helvetica-Bold").fontSize(7.5).fillColor("black")
    .text("Phone: ", margin + 15, contactLineY, { continued: true })
    .font("Helvetica").text("+91-9840582365", { continued: false });

  doc.font("Helvetica-Bold").fontSize(7.5)
    .text(`Report Date: ${reportDate}`, margin, contactLineY, { align: "center", width: contentWidth });

  const emailX = pageWidth - margin - 120;
  doc.font("Helvetica-Bold").fontSize(7.5)
    .text("Email: ", emailX, contactLineY, { continued: true })
    .font("Helvetica").text("admin@vyuhaadata.com", { continued: false });
};

const drawPatientInfo = (doc, data, specimenType) => {
  const gridY = 160;
  doc.rect(margin, gridY, contentWidth, 75).fill(lightBlueBg);

  const drawField = (label, value, xL, xV, y) => {
    doc.fillColor(blueColor).font("Helvetica-Bold").fontSize(8.5).text(label, xL, y);
    doc.fillColor("black").font("Helvetica-Bold").fontSize(8.5).text(value || "N/A", xV, y);
  };

  let rY = gridY + 10;
  drawField("Patient Name:", data.patient_name, margin + 20, margin + 135, rY);
  drawField("Age / Sex:", `${data.age || "N/A"} / ${data.gender || "N/A"}`, margin + 310, margin + 410, rY);
  rY += 16;
  drawField("Patient MR# / Barcode:", data.barcode || data.mr_number, margin + 20, margin + 135, rY);
  drawField("Hospital/Camp:", data.hospital_name, margin + 310, margin + 410, rY);
  rY += 16;
  drawField("Ordered by:", data.doctor_name, margin + 20, margin + 135, rY);
  drawField("Specimen Type:", specimenType, margin + 310, margin + 410, rY);
  rY += 16;
  drawField("Collection Date:", data.collection_date || "N/A", margin + 20, margin + 135, rY);
  drawField("Report Status:", "Final", margin + 310, margin + 410, rY);
};

const drawFooter = (doc) => {
  const footerY = 785;
  doc.moveTo(margin, footerY - 5).lineTo(pageWidth - margin, footerY - 5)
    .strokeColor("#eeeeee").lineWidth(0.5).stroke();

  doc.fillColor("#777777").font("Helvetica-Bold").fontSize(7.5)
    .text("This report has been generated by CerviAI, Vyuhaa Med Data Private Limited, Vishakhapatnam",
      margin, footerY, { align: "center", width: contentWidth });

  doc.font("Helvetica")
    .text("ISO 13485 & ISO 15189:2012 Certified facilities | NABL Accredited Lab Services | AI-Enhanced Accuracy",
      margin, footerY + 10, { align: "center", width: contentWidth });
};

const drawLocalImage = (doc, dbPath, xPos, yPos, width, height) => {
  if (!dbPath) return;
  const cleanPath = dbPath.startsWith("/") ? dbPath.substring(1) : dbPath;
  const absolutePath = path.resolve(process.cwd(), cleanPath);
  if (fs.existsSync(absolutePath)) {
    doc.image(absolutePath, xPos, yPos, { width, height });
    doc.rect(xPos, yPos, width, height).strokeColor("#cccccc").lineWidth(0.5).stroke();
  } else {
    doc.rect(xPos, yPos, width, height).fill("#f5f5f5").stroke("#cccccc");
    doc.fillColor("#aaaaaa").font("Helvetica-Oblique").fontSize(8)
      .text("[Image not available]", xPos + 10, yPos + height / 2 - 5, { width: width - 20 });
  }
};

// ─── PAGE 1: LBC REPORT ───────────────────────────────────────────────────────

const drawLBCPage = (doc, data) => {
  const reportDate = getReportDate();

  drawHeader(doc, reportDate);

  // Title
  doc.fillColor(blueColor).font("Helvetica-Bold").fontSize(13)
    .text("LIQUID BASED CYTOLOGY REPORT", margin, 135, { align: "center" });

  drawPatientInfo(doc, data, data.specimen_type || "LBC");

  // Sections
  let currentY = 250;

  const drawSection = (title, content, y) => {
    doc.fillColor(sectionHeaderColor).font("Helvetica-Bold").fontSize(9).text(title, margin + 10, y);
    doc.fillColor("black").font("Helvetica").fontSize(8.5)
      .text(content || "N/A", margin + 15, y + 12, { width: contentWidth - 40 });
    return doc.y + 12;
  };

  currentY = drawSection("SPECIMEN ADEQUACY", data.specimen_adequacy, currentY);
  currentY = drawSection("CLINICAL HISTORY", data.clinical_history, currentY);

  // Microscopic Description
  doc.fillColor(sectionHeaderColor).font("Helvetica-Bold").fontSize(9)
    .text("MICROSCOPIC DESCRIPTION", margin + 10, currentY);
  currentY += 14;

  if (data.microscopy_list && Array.isArray(data.microscopy_list)) {
    data.microscopy_list.forEach((item) => {
      doc.fillColor("black").font("Helvetica").fontSize(8.5).text("•", margin + 15, currentY);
      doc.text(item, margin + 25, currentY, { width: contentWidth - 40 });
      currentY = doc.y + 4;
    });
  }
  currentY += 10;

  // Result Box
  doc.fillColor(sectionHeaderColor).font("Helvetica-Bold").fontSize(9)
    .text("CLINICAL IMPRESSION / RESULT", margin + 10, currentY);
  currentY += 14;
  doc.rect(margin + 10, currentY, contentWidth - 20, 26).fill("#fcfcfc").stroke("#dddddd");
  doc.fillColor("black").font("Helvetica-Bold").fontSize(10)
    .text(data.result || "NILM", margin + 20, currentY + 8);
  currentY += 38;

  // Follow-up
  doc.fillColor(sectionHeaderColor).font("Helvetica-Bold").fontSize(9)
    .text("FOLLOW-UP RECOMMENDATION", margin + 10, currentY);
  currentY += 14;
  const followUps = Array.isArray(data.recommendations_list) ? data.recommendations_list : ["Routine screening."];
  doc.fillColor("black").font("Helvetica").fontSize(8.5)
    .text(`• ${followUps.join(", ")}`, margin + 15, currentY, { width: contentWidth - 40 });
  currentY = doc.y + 4;

  // LBC Images
  currentY += 15;
  const imgWidth = 180;
  const imgHeight = 110;
  doc.fillColor(sectionHeaderColor).font("Helvetica-Bold").fontSize(9)
    .text("LBC DIGITAL IMAGES:", margin + 10, currentY);

  drawLocalImage(doc, data.image1_path, margin + 40, currentY + 12, imgWidth, imgHeight);
  drawLocalImage(doc, data.image2_path, margin + 40 + imgWidth + 40, currentY + 12, imgWidth, imgHeight);
  currentY += imgHeight + 35;

  // Notes box
  const notesWidth = 260;
  const notesX = pageWidth - margin - notesWidth;
  doc.rect(notesX, currentY, notesWidth, 100).fill("#f8fbff").stroke("#e3f2fd");
  doc.fillColor("black").font("Helvetica-Bold").fontSize(7.6).text("IMPORTANT NOTE", notesX + 10, currentY + 8);

  const importantNotes = [
    "Clinical correlation: Please correlate clinically.",
    "Adequacy Standards: Minimum 5,000 squamous cells for LBC.",
    "Quality Assurance: Transformation zone sample requires >=10 endocervical cells.",
    "Note: Cervix smear cytology is a screening test. Associated false results may occur.",
    "Reference: BETHESDA System, 3rd Edition.",
  ];
  let noteY = currentY + 18;
  importantNotes.forEach((note) => {
    doc.fillColor("#444444").font("Helvetica").fontSize(6.5)
      .text(`• ${note}`, notesX + 10, noteY, { width: notesWidth - 20, lineGap: 1 });
    noteY = doc.y + 2.5;
  });

  // Signature
  try {
    const sigPath = path.resolve(process.cwd(), "assets", "sunita_sig.png");
    if (fs.existsSync(sigPath)) doc.image(sigPath, margin + 10, currentY, { width: 80 });
  } catch (e) {}

  drawFooter(doc);
};

// ─── PAGE 2: HPV REPORT ───────────────────────────────────────────────────────

const drawHPVPage = (doc, data) => {
  const reportDate = getReportDate();

  drawHeader(doc, reportDate);

  // Title
  doc.fillColor(blueColor).font("Helvetica-Bold").fontSize(13)
    .text("HPV DNA - REAL TIME PCR REPORT", margin, 135, { align: "center" });

  drawPatientInfo(doc, data, "HPV");

  // Molecular Biology Table
  let currentY = 255;

  doc.fillColor(blueColor).font("Helvetica-Bold").fontSize(14)
    .text("MOLECULAR BIOLOGY", margin, currentY, { align: "center", width: contentWidth });
  currentY += 22;

  const tableX = margin + 10;
  const tableWidth = contentWidth - 20;
  const col1W = tableWidth * 0.6;

  // Table header
  doc.rect(tableX, currentY, tableWidth, 20).fill("#1565c0");
  doc.fillColor("white").font("Helvetica-Bold").fontSize(9)
    .text("TEST DESCRIPTION", tableX + tableWidth * 0.3 - 40, currentY + 6, { width: col1W, align: "center" });
  doc.fillColor("white").font("Helvetica-Bold").fontSize(9)
    .text("RESULT", tableX + col1W, currentY + 6, { width: tableWidth - col1W, align: "center" });
  currentY += 20;

  // Sub-header
  doc.rect(tableX, currentY, tableWidth, 28).fill("#ddeeff");
  doc.fillColor("black").font("Helvetica-Bold").fontSize(8.5).text("HPV DNA - Real Time PCR", tableX + 10, currentY + 5);
  doc.fillColor("#555555").font("Helvetica-Oblique").fontSize(7.5).text("(Method: Real Time PCR)", tableX + 10, currentY + 16);
  currentY += 28;

  // HPV test rows
  const hpvTests = [
    { test: "HPV - 16", result: data.hpv16 || "NOT DETECTED" },
    { test: "HPV - 18", result: data.hpv18 || "NOT DETECTED" },
    { test: "HPV - OTHER HIGH RISK", result: data.hr_hpv || "NOT DETECTED" },
  ];

  hpvTests.forEach((row, i) => {
    const rowBg = i % 2 === 0 ? "#e8f4fb" : "#f5f9ff";
    doc.rect(tableX, currentY, tableWidth, 20).fill(rowBg).stroke("#d0e4f0");
    doc.fillColor(blueColor).font("Helvetica-Bold").fontSize(8.5).text(row.test, tableX + 10, currentY + 6);
    doc.fillColor("black").font("Helvetica-Bold").fontSize(8.5)
      .text(row.result.toUpperCase(), tableX + col1W, currentY + 6, { width: tableWidth - col1W, align: "center" });
    currentY += 20;
  });
  currentY += 14;

  // PCR Plot + Interpretation
  const plotX = margin + 10;
  const plotWidth = 250;
  const plotHeight = 170;
  const interpX = plotX + plotWidth + 15;
  const interpWidth = contentWidth - plotWidth - 25;
  const sectionStartY = currentY;

  doc.fillColor(sectionHeaderColor).font("Helvetica-Bold").fontSize(9)
    .text("PCR AMPLIFICATION PLOT", plotX, sectionStartY);

  // HPV image is image3_path for co-test
  drawLocalImage(doc, data.image3_path , plotX, sectionStartY + 14, plotWidth, plotHeight);

  // Interpretation table
  doc.fillColor(sectionHeaderColor).font("Helvetica-Bold").fontSize(9)
    .text("INTERPRETATION", interpX, sectionStartY);

  let interpY = sectionStartY + 14;
  doc.rect(interpX, interpY, interpWidth, 16).fill("#1565c0");
  doc.fillColor("white").font("Helvetica-Bold").fontSize(7.5).text("RESULT", interpX + 5, interpY + 4);
  doc.text("MEANING", interpX + interpWidth * 0.4, interpY + 4);
  interpY += 16;

  const interpRows = [
    { result: "Detected", meaning: "Sample contains HPV DNA" },
    { result: "Indeterminate", meaning: "Presence of inhibitors in the sample" },
    { result: "Not Detected", meaning: "No HPV DNA, or copies below detection limit" },
  ];

  interpRows.forEach((row, i) => {
    const rowBg = i % 2 === 0 ? "#f5f9ff" : "#ffffff";
    doc.rect(interpX, interpY, interpWidth, 24).fill(rowBg).stroke("#e0e0e0");
    doc.fillColor("black").font("Helvetica-Bold").fontSize(9).text(row.result, interpX + 5, interpY + 7);
    doc.fillColor("#333333").font("Helvetica").fontSize(8)
      .text(row.meaning, interpX + interpWidth * 0.4, interpY + 7, { width: interpWidth * 0.58, lineGap: 1 });
    interpY = Math.max(interpY + 24, doc.y + 2);
  });

  interpY += 6;
  doc.fillColor("#333333").font("Helvetica-Bold").fontSize(7.5)
    .text("Specifications: Real-Time PCR with ROX CY5 VIC FAM channels", interpX, interpY, { width: interpWidth });
  interpY = doc.y + 4;
  doc.fillColor("#333333").font("Helvetica-Bold").fontSize(7.5)
    .text("CDSCO Approved: IVD MFG/IVD/2024/000059", interpX, interpY, { width: interpWidth });

  currentY = sectionStartY + 14 + plotHeight + 20;

  // Notes
  doc.fillColor(sectionHeaderColor).font("Helvetica-Bold").fontSize(9)
    .text("NOTES:", margin + 10, currentY);
  currentY += 12;
  doc.fillColor("#333333").font("Helvetica").fontSize(8.5)
    .text(data.notes || data.clinical_history || "None provided.", margin + 15, currentY, { width: contentWidth - 30 });
  currentY = doc.y + 24;

  // Signature
  try {
    const sigPath = path.resolve(process.cwd(), "assets", "sunita_sig.png");
    if (fs.existsSync(sigPath)) doc.image(sigPath, margin + 10, currentY, { width: 110 });
  } catch (e) {}

  drawFooter(doc);
};

// ─── MAIN EXPORT ──────────────────────────────────────────────────────────────

export const generateCoTestReport = (data, stream) => {
  const doc = new PDFDocument({
    size: "A4",
    autoFirstPage: false,
    margin: { top: 30, left: 30, right: 30, bottom: 20 },
  });

  doc.pipe(stream);

  // Page 1 — LBC
  doc.addPage();
  drawLBCPage(doc, data);

  // Page 2 — HPV
  doc.addPage();
  drawHPVPage(doc, data);

  doc.end();
};
